//! 최근 세션 목록 — "어느 프로젝트에서 얼마나 태웠나".
//!
//! 벤더 페이지는 벤더 단위라 프로젝트를 모르고, 통계 페이지는 날짜 단위라 무엇을
//! 했는지를 모른다. 이 목록만 그 질문에 답한다.
//!
//! 세 CLI 모두 작업 디렉토리를 정확히 남긴다 — 경로를 되짚어 추측할 필요가 없다:
//!
//! | | 세션 id | 작업 위치 | 브랜치 | 제목 |
//! |---|---|---|---|---|
//! | Claude | 트랜스크립트의 `sessionId` | 같은 행의 `cwd` | `gitBranch` | **첫 사람 메시지** (명령 래퍼 제외) |
//! | Codex | `session_meta.payload.id` | `session_meta.payload.cwd` | `session_meta.payload.git.branch` | **첫 `user_message`** |
//! | Antigravity | 대화 uuid | 첫 스텝의 `19.12.12` | 없음 | **첫 스텝의 `19.2`** (첫 사용자 메시지) |
//!
//! 제목은 셋 다 **첫 사용자 메시지**라는 같은 규칙을 쓴다 ([`first_line`] 으로 정제).

use chrono::{DateTime, Utc};
use serde::Serialize;

use crate::model::Source;

/// 최근 세션 한 줄
#[derive(Clone, Debug, Serialize)]
pub struct SessionRow {
    pub source: Source,
    /// 세션/대화 id — 목록 키
    pub id: String,
    /// 화면에 뜨는 이름. 첫 사용자 메시지가 있으면 그것, 없으면 작업 폴더 이름.
    pub label: String,
    /// 작업 디렉토리 전체 경로 (툴팁용, 없으면 빈 문자열)
    pub cwd: String,
    /// 이 세션에서 마지막으로 쓴 모델
    pub model: String,
    /// git 브랜치 — Claude·Codex 가 알려준다 (agy 는 없음)
    pub branch: String,
    /// 마지막 활동 시각
    pub at: DateTime<Utc>,
    /// 이 세션이 쓴 토큰 총합 (스캔 범위 안에서)
    pub tokens: u64,
}

/// 경로에서 표시용 이름 하나를 뽑는다. 구분자가 OS마다 다르고 agy 는 `file://` URI 로
/// 주므로 둘 다 받아들인다. 마지막 조각이 비면(끝에 구분자) 그 앞을 쓴다.
pub fn dir_label(path: &str) -> String {
    let cleaned = path.trim_end_matches(['/', '\\']);
    cleaned
        .rsplit(['/', '\\'])
        .find(|s| !s.is_empty())
        .unwrap_or(cleaned)
        .to_string()
}

/// 사람이 실제로 친 프롬프트로 볼 만한가 — 제목 후보를 거르는 공통 규칙.
///
/// 세 소스 모두 "사용자 메시지" 자리에 사람이 친 것 말고도 다른 게 들어온다 (전부 실측):
///
/// ```text
/// <local-command-caveat>Caveat: The messages below were generated by the user…
/// <command-name>/model</command-name>
/// <local-command-stdout>Set model to Opus 5…
/// <task-notification>…
/// [Request interrupted by user for tool use]
/// ```
///
/// Claude 는 자기 트랜스크립트에 이걸 직접 남기고, **Codex 도 같은 것이 들어온다** —
/// 다른 도구가 Claude 대화 내용을 그대로 입력으로 넣은 세션이 실측됐다 (`Codex Desktop`
/// originator, 50건). 그래서 소스별로 따로 두지 않고 여기 한 곳에 둔다.
///
/// 태그는 도구의 내부 포맷이라 바뀔 수 있다. 못 걸러도 **제목이 이상해질 뿐 집계엔 영향이
/// 없다.** 반대로 `<div>` 로 시작하는 정상 질문을 잃을 수 있지만, 실측 159건 중 그런
/// 경우는 없었고 래퍼는 60건 넘게 있었다.
pub fn is_human_prompt(text: &str) -> bool {
    let t = text.trim_start();
    if t.is_empty() {
        return false;
    }
    // 명령 래퍼·시스템 주입은 전부 태그로 시작한다
    if t.starts_with('<') {
        return false;
    }
    // `[Request interrupted…]` 처럼 대괄호로만 된 시스템 문구
    if t.starts_with('[') && t.trim_end().ends_with(']') {
        return false;
    }
    true
}

/// 제목 후보(첫 사용자 메시지)를 한 줄짜리 라벨로 정제한다.
///
/// 실측에서 첫 메시지에 줄바꿈·코드블록·붙여넣은 JSON 이 그대로 들어옵니다 — 그대로 쓰면
/// 목록 한 줄이 통째로 무너진다. **첫 비어 있지 않은 줄**만 쓰고 길이도 자른다
/// (붙여넣기 한 덩어리가 통째로 요약 payload 에 실려 IPC 로 나가지 않도록).
pub fn first_line(text: &str) -> String {
    let line = text.lines().map(str::trim).find(|l| !l.is_empty()).unwrap_or("");
    // 한글은 멀티바이트라 바이트로 자르면 안 된다
    line.chars().take(TITLE_MAX_CHARS).collect::<String>().trim_end().to_string()
}

/// 라벨 길이 상한. 화면은 CSS 로 더 줄이지만, 그 전에 payload 크기를 잡아 둔다.
const TITLE_MAX_CHARS: usize = 80;

/// `file:///C:/Users/x/proj` → `C:/Users/x/proj` (agy 의 workspace_uris 형식)
pub fn from_file_uri(uri: &str) -> String {
    let s = uri.strip_prefix("file://").unwrap_or(uri);
    // Windows 경로는 `file:///C:/...` 라 앞에 슬래시가 하나 더 붙는다
    let s = if s.len() > 2 && s.starts_with('/') && s.as_bytes()[2] == b':' { &s[1..] } else { s };
    percent_decode(s)
}

/// 공백 등이 `%20` 으로 인코딩돼 오므로 되돌린다. 의존성을 늘리지 않으려고 직접 구현.
fn percent_decode(s: &str) -> String {
    let b = s.as_bytes();
    let mut out = Vec::with_capacity(b.len());
    let mut i = 0;
    while i < b.len() {
        if b[i] == b'%' && i + 2 < b.len() {
            if let Ok(v) = u8::from_str_radix(&s[i + 1..i + 3], 16) {
                out.push(v);
                i += 3;
                continue;
            }
        }
        out.push(b[i]);
        i += 1;
    }
    String::from_utf8(out).unwrap_or_else(|_| s.to_string())
}

/// 여러 소스의 세션을 최근순으로 합친다. 같은 id 는 한 번만 (복사본 대비).
pub fn merge(mut rows: Vec<SessionRow>, limit: usize) -> Vec<SessionRow> {
    rows.sort_by(|a, b| b.at.cmp(&a.at));
    let mut seen = std::collections::HashSet::new();
    rows.retain(|r| seen.insert((r.source, r.id.clone())));
    rows.truncate(limit);
    rows
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dir_label_handles_both_separators() {
        assert_eq!(dir_label(r"C:\Users\u\projects\token-chan"), "token-chan");
        assert_eq!(dir_label("/home/u/projects/api"), "api");
        assert_eq!(dir_label("/home/u/projects/api/"), "api");
        assert_eq!(dir_label("solo"), "solo");
        assert_eq!(dir_label(""), "");
    }

    /// 첫 메시지에 줄바꿈·코드블록이 섞여 오는 건 실측된 사실이다 (Codex rollout).
    /// 그대로 라벨에 넣으면 목록 한 줄이 무너진다.
    #[test]
    fn first_line_takes_one_clean_line() {
        assert_eq!(first_line("codex cli의 상태 정보\n{\n  \"a\": 1\n}"), "codex cli의 상태 정보");
        assert_eq!(first_line("  \n\n  앞이 비어 있음  \n뒤"), "앞이 비어 있음");
        assert_eq!(first_line(""), "");
        assert_eq!(first_line("\n\n"), "");
    }

    /// 도구가 주입한 래퍼는 제목이 되면 안 된다. 세 소스 모두 같은 규칙을 쓴다 —
    /// Claude 는 자기 트랜스크립트에, Codex 는 다른 도구가 넣은 입력에 이게 들어온다.
    #[test]
    fn is_human_prompt_rejects_tool_wrappers() {
        assert!(!is_human_prompt("<command-name>/usage</command-name>"));
        assert!(!is_human_prompt("<local-command-stdout>Set model to Opus 5</local…>"));
        assert!(!is_human_prompt("  <local-command-caveat>Caveat: …"));
        assert!(!is_human_prompt("<task-notification>\n<task-id>abc</task-id>"));
        assert!(!is_human_prompt("[Request interrupted by user for tool use]"));
        assert!(!is_human_prompt("   "));

        assert!(is_human_prompt("현재 프로젝트에서 개선할 부분들이 남았는지??"));
        assert!(is_human_prompt("A부터 진행."));
        // 대괄호로 **시작만** 하는 건 사람 문장일 수 있다
        assert!(is_human_prompt("[중요] 이거 먼저 봐주세요"));
    }

    /// 붙여넣은 한 덩어리가 통째로 요약 payload 에 실려 나가지 않게 자른다.
    /// 한글은 멀티바이트라 바이트가 아니라 문자 수로 잘라야 한다.
    #[test]
    fn first_line_caps_length_on_char_boundary() {
        let long = "가".repeat(200);
        let out = first_line(&long);
        assert_eq!(out.chars().count(), TITLE_MAX_CHARS);
        assert!(out.len() > TITLE_MAX_CHARS, "바이트 길이는 문자 수보다 크다 (잘못 자르면 패닉)");
    }

    #[test]
    fn file_uri_becomes_a_path() {
        // agy 가 실제로 주는 형태
        assert_eq!(from_file_uri("file:///C:/Users/u"), "C:/Users/u");
        assert_eq!(from_file_uri("file:///home/u/proj"), "/home/u/proj");
        assert_eq!(from_file_uri("file:///C:/my%20proj"), "C:/my proj");
        // URI 가 아니면 그대로
        assert_eq!(from_file_uri("/plain/path"), "/plain/path");
    }

    fn row(source: Source, id: &str, at: &str) -> SessionRow {
        SessionRow {
            source,
            id: id.into(),
            label: id.into(),
            cwd: String::new(),
            model: String::new(),
            branch: String::new(),
            at: DateTime::parse_from_rfc3339(at).unwrap().with_timezone(&Utc),
            tokens: 0,
        }
    }

    #[test]
    fn merge_sorts_recent_first_and_dedups() {
        let out = merge(
            vec![
                row(Source::Claude, "a", "2026-08-11T01:00:00Z"),
                row(Source::Codex, "b", "2026-08-11T03:00:00Z"),
                row(Source::Claude, "a", "2026-08-11T02:00:00Z"), // 같은 세션의 복사본
                row(Source::Antigravity, "c", "2026-08-11T02:30:00Z"),
            ],
            10,
        );
        assert_eq!(out.len(), 3, "같은 소스·id 는 한 번만");
        assert_eq!(out[0].id, "b");
        assert_eq!(out[1].id, "c");
        // 복사본 중에서는 더 최근 것이 남아야 한다
        assert_eq!(out[2].at.to_rfc3339(), "2026-08-11T02:00:00+00:00");
    }

    #[test]
    fn merge_respects_limit() {
        let rows: Vec<SessionRow> = (0..20)
            .map(|i| row(Source::Claude, &format!("s{i}"), "2026-08-11T01:00:00Z"))
            .collect();
        assert_eq!(merge(rows, 8).len(), 8);
    }
}
